### ISSUE TITLE
`pass_struct` keyword not available anymore

### ISSUE THREAD

**Issue by sibirrer** [johannesulf/nautilus#17]
Hi @johannesulf, the keyword `pass_struct` is not available anymore in Samper() and I don't know with what to replace it such that the tests with a very short runtime/iteration pass in the tests in lenstronomy. I really don't want to have too much work making nautilus integration tests pass in lenstronomy.

Thank you very much!
Simon

**Comment by johannesulf** [comment]
@sibirrer Yes, sorry for that breaking change. Just replace is with `pass_dict`.

**Comment by johannesulf** [comment]
This issue actually uncovered a bug in nautilus that's fixed in version 0.4.1.
