### ISSUE TITLE
initialize the pool 

### ISSUE THREAD

**Issue by Jane550** [johannesulf/nautilus#41]
Hi Johannes! The likelihood function in my case is very complex, and one of the reasons for its complexity is that it includes reading the data from an h5 file. Therefore, each time I call the likelihood function in parallelization I will need to open the h5 file, which I guess is very time-consuming. I plan to read the file to an array once and for all (the data is the same for every worker), and then for every process calling the likelihood with a different set of parameters, I can start from the array in the memory. Is what I want to do to 'initialize the pool'?
Now I am using MPIPool from Schwimmbad. The structure is like this:
```
if __name__ == '__main__': 
    with MPIPool() as pool:
        if not pool.is_master():
            pool.wait()
            sys.exit(0)
        sampler = Sampler(prior, log_likelihood, n_dim=7, n_live=2000, seed=42, filepath='nautilus-record-true-1120.hdf5', pool=pool) 
        sampler.run(verbose=True, discard_exploration=True)
```
Maybe I need to add something to this structure?

**Comment by johannesulf** [comment]
Thanks for reaching out. Unfortunately, I'm not that familiar with Schwimmbad. Additionally, I'd need to know a bit more about your problem to understand whether the above code will give a decent performance. The above code will most likely not require you to read a file during every likelihood call. However, it may still require to transfer of memory from the main to the sub-processes during every call. This can be a severe bottleneck in many situations.

Do you actually need MPI, i.e., are you trying to parallelize over multiple nodes of a cluster? If you just want to parallelize over multiple cores of a CPU, you could use Nautilus' internal SMP parallelization which takes care of this issue.

**Comment by johannesulf** [comment]
If you use the SMP parralelization, i.e., `pool=72`, nothing else needs to be done. Nautilus will internally distribute the likelihood function to all workers. Regarding the second question: `pool=(72,72)` and `pool=72` should basically perform equally well since they both distribute internal Nautilus calculations and likelihood computations over 72 cores. The only difference is that the former has two separate pools. But this shouldn't really make a difference.

**Comment by johannesulf** [comment]
Not quite, actually. You still need to make sure to write your function in such a way that a call to `log_likelihood` will not trigger reading in a file for every likelihood call. Currently, your code still does that, it seems. Sorry if I misunderstood you initially.

**Comment by Jane550** [comment]
Yeah, the code now does read the file in every call. I thought SMP could automatically take care of that, which confused me a lot. So my question is where should I put the reading file part such that the code only reads it once.

**Comment by johannesulf** [comment]
What the SMP implementation of Nautilus can take of is that you don't have to send the likelihood function and associated data from the main to the sub-process during each likelihood call. However, it does not take care of how you read in the data. This is outside the scope of what Nautilus does.

One way to implement this is that you could read in the file and then have the likelihood function take the data as an additional argument, i.e., `def log_likelihood(data, param_dict):` and then add `likelihood_args=[data, ]` when initializing the sampler.

**Comment by johannesulf** [comment]
I think you probably correctly initialized the pool and that not all cores are used all the time is expected. First, nautilus processes likelihood evaluations in batches. The default batch size is 100. For 72 CPU cores, that means that for each batch, the first 72 are processed by all cores whereas there are another 28 evaluations that only keep 28 cores busy. So choose a batch size that's a multiple of 72, i.e., 72 or 144. You can set this with `n_batch=72`. Additionally, not all parts of nautilus can make use of all cores. But I hope that most of the time, you're using 72 cores.

**Comment by Jane550** [comment]
Thank! And I noticed in the doc that by setting 'vectorized=True', the likelihood function can receive multiple input sets at once. Is this something like the parallelism, where we call likelihood for different parameters simultaneously.

**Comment by johannesulf** [comment]
No, vectorization is something different. It refers to likelihood functions that can be sped up through the use of NumPy vectorization. I don't think this applies to you. I've also implemented it in such a way that parallelization is turned off if vectorization is turned on. So make sure to set `vectorized=False`. I don't quite understand your second question. But let me clarify that each process solves every likelihood evaluation one by one. It never solves 2 likelihoods simultaneously (unless you use vectorization).

**Comment by Jane550** [comment]
Okay, I understood now. By setting b_batch multiple times of the cores I used, and read in the data once in 'likelihood_args' am I making the most of the Nautilus SMP parallel structure then? Is there any other thing I can improve to speed up regardless of the specific form of the likelihood function.

**Comment by johannesulf** [comment]
No, I think what we discussed should take care of the most important performance aspects.

**Comment by johannesulf** [comment]
Under normal circumstances, there shouldn't be a big difference between the different batch sizes. The only real difference for the algorithm is that with larger batch sizes you will get new boundaries a little later since new boundaries are only created after a certain number of high-likelihood points are found (and only after a batch is finished). In practice, if your likelihood evaluations have variable execution times, larger batch sizes may be better. For example, let's assume your likelihood evaluation time can vary from 0.5 seconds to 3 seconds per core. With a batch size of 72, the whole batch would be determined by the largest value, i.e., 3 seconds. In other words, those cores that have a fast likelihood call are idle during most of the time. However, with a batch size of 216, the relative variation in the computation time may be less since every core solves 3 likelihoods, on average.

**Comment by Jane550** [comment]
I see. As I understood, the most appropriate batch_size actually vary for different cases. We will have to try to find the best value balancing evaluating the likelihood and finding new points in the correct direction, is that the spirit? 
And here is a small question that is not that relavant to this issue. Is it possible to resume the sampling process for an extended parameter space? For example, my former parameter space is $a\in [9,11]$, and $b\in [10,12]$. Then I found in the corner plot that maximum likelihood estimate for b is quite at the edge, say $b=10.01$, it could be even smaller than 10. In this case I would like to extend the boundaries for $b$ to $[8,12]$, for example. Then do I have to recalculate the likelihood all over or can I make use of the points in the former region that already have a likelihood evaluated.

**Comment by johannesulf** [comment]
No, if you change your prior, you have to re-run from scratch. In principle, one could use results from the first run but this isn't implemented right now. Also, I don't think there are many samplers that would support such a scenario.

**Comment by Jane550** [comment]
Okay. Thanks for your patience!
