### ISSUE TITLE
Extra parameter output

### ISSUE THREAD

**Issue by ShimingGu** [johannesulf/nautilus#51]
Hi Johannes,

Is there any way in the Nautilus to return the posterior of derived parameters (for a common example, a $\sigma_8$ posterior when sampling over a prior with $A_s$)?
 
Thanks!

**Comment by johannesulf** [comment]
@ShimingGu Yes, that's what's called blobs in nautilus (https://nautilus-sampler.readthedocs.io/en/latest/guides/blobs.html). Coincidentally, this feature was first implemented to get posteriors of derived cosmological parameters such as sigma_8. Please let me know if you have any questions.

**Comment by ShimingGu** [comment]
@johannesulf Thanks!
