### ISSUE TITLE
specifying cyclic parameters?

### ISSUE THREAD

**Issue by ajdittmann** [johannesulf/nautilus#56]
Would it be reasonable to add support for wrapped / cyclic parameters? I would personally find it quite useful.

**Comment by johannesulf** [comment]
Hi @ajdittmann, thanks for reaching out! This is certainly a feature I was contemplating for a bit. Can you tell me a bit more about your use case? How many parameters do you have overall and how many are wrapped? My understanding is that support for periodic parameters would "only" increase the sampling efficiency, particularly in cases that the posterior is centered on the bounds. Have you tried modifying your parameters such that the posterior is not centered on the boundary? That would give us some idea of how much support for cyclic parameters would improve things.

**Comment by ajdittmann** [comment]
The simplest model I'm interested in has 1 cyclic parameter out of 12, but the more complicated ones can have 4 out of 16 or 7 out of 30. 
In addition to the sampling efficiency, I am concerned about individual modes being split in twain, making it more challenging for the sampler to identify all relevant modes and to achieve converged results, lengthening the process of testing convergence. 
In principle, if after an initial run the posterior appears appears peaked near one of the boundaries, the parameters could be modified and the model could be rerun. However, the posterior is not always tightly peaked enough for this to be useful, and in any case it would be better to avoid the additional expense incurred by these additional analyses.

**Comment by johannesulf** [comment]
Thanks! I wasn't recommending that you should always re-run the analysis such that the peak wasn't at the boundary. I was just curious whether you had tested that since it would give us some idea of how much specifying periodic parameters would improve efficiency/convergence.

Unfortunately, I don't think all parts of the algorithm (minimum-volume enclosing ellipsoids, Gaussian Mixture, neural networks etc.) will work with periodic parameters. However, I have some ideas of how runs with periodic parameters could be improved. I'll look into this in the coming weeks.

**Comment by ajdittmann** [comment]
I've put together a problem to try and test this a little more quantitatively but it will be a while before I have good data - the decreased efficiency makes the misparameterized version take quite a bit longer, at least. 
Since many other nested sampling packages (mutlinest, dynesty, ultranest, etc.) implement periodic boundaries I suspect the minimum-volume ellipsoids part should be reasonably straightforward.
Thanks for looking into this, I look forward to seeing what you come up with.

**Comment by ajdittmann** [comment]
Wonderful, this should be very helpful, although I won't be able to use it in my research until writing to disk and restarting are supported.

Still, it seems to work very well for test problems. I put together a little 10D shifted hyper-gaussian test (^6 instead of ^2).

- Centering the distributions, sampling with 3k live points took about 18 minutes and had a log evidence error on the order of 0.02. In this case, only one ellipse is needed.
- Shifting the distributions to center near the edge of the prior so they loop around, but **not** specifying that the bounds should be periodic, the sampler is still struggling after a few hours and seems to have reached 34 ellipses and 44 networks. 
- On the other hand, when shifting the distributions and specifying that each parameter was periodic the sampler finished in about 18 minutes (actually about 6 seconds faster than the unshifted run) and only required one ellipse and 4 networks.

**Comment by johannesulf** [comment]
@ajdittmann Thanks so much for testing this. I implemented all features and fixed a minor bug. So the feature should hopefully be completely usable now. That said, it's going to be a bit before I will release this feature on PyPI and conda. I will probably wait until I finish a new 1.1 version of `nautilus`. Of course, you're free to use this version in the `periodic` branch until then.

**Comment by ajdittmann** [comment]
Not sure if this is worth a new issue or not, but the current implementation requires the periodic parameters to have the lower indices than non-periodic parameters, which seems kind of annoying. 
For example, if I run something passing periodic = np.array([0,1]) for a 3D model, things work fine, but if I try periodic=np.array([1,2]) I get an index error in `compute`.

Presumably the best fix would be changing https://github.com/johannesulf/nautilus/blob/main/nautilus/bounds/periodic.py#L42C1-L42C29 to an enumerate() or something equivalent, since `bound.centers[dim]` will currently go out of bounds when the index of a periodic parameter is greater than the number of periodic parameters.
