### ISSUE TITLE
jobs submitted via slurm stall

### ISSUE THREAD

**Issue by ajdittmann** [johannesulf/nautilus#58]
I have tried to submit a number of jobs using slurm, and in every case the jobs stall, failing to produce any output. This holds for single-node jobs, multi-node jobs, realistic problems and simple tests. I've encountered the same issue on two different clusters. 

As a simple test, I've been using the following python script, which works fine using MPI on my laptop:
```
import numpy as np
import time
from nautilus import Prior, Sampler
from schwimmbad import MPIPool
import sys

prior = Prior()
for i in range(3):
  prior.add_parameter()

def logl(x):
  return np.sum( -(x-0.5)**2/0.02)

mypool = MPIPool()
if not mypool.is_master():
  mypool.wait()
  sys.exit()

sampler = Sampler(prior, logl, pass_dict=False, pool=mypool)
start = time.time()
sampler.run(verbose=True)
end = time.time()
print(end-start)
```
this example uses the schwimmbad package for the MPI pool, but I've encountered the same error using the method suggested [here](https://nautilus-sampler.readthedocs.io/en/latest/guides/parallelization.html#mpi-parallelization). On my laptop this works as expected, produces a result, etc. 

Through slurm I get output as normal for a minute or two, but the things seem to freeze with a state like the one below:
```
Status         | Bounds | Ellipses | Networks | Calls    | f_live    | N_eff | log Z                                                                                  
Computing |             2|         1    |         4       |   4896  | 0.9997 | 238   | -4.28 
```
This would be the final thing printed to the slurm output until the submission timeout message. When I also employ checkpointing, the hdf5 file ceases to update at about the same time. 

The only difference I have seen from one cluster to another is that some do not like carriage returns and the output garbled. 
SSHing into the job where the job is running and then using top suggests that the processes are still active and doing _something_.

I'd appreciate any suggestions, or ideas on figuring out which part of the sampling procedure is failing.

**Comment by johannesulf** [comment]
Thanks for reporting this. I'll try to look into that. It's strange that it works on your laptop but not on a cluster. So this may be a bit harder to figure out.

**Comment by ajdittmann** [comment]
I'll close this for now - I was able to get things to work by using the pool only for likelihood calculations and not for the sampler.

**Comment by johannesulf** [comment]
Good to know! Thanks! This gives me a clue where the issue might lie.
